# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
restartPolicy: Always
version: 0.1.2
environment: stage

env:
  GOOGLE_PROJECT: myproject

secrets:
  - envName: AWS_SECRET_ACCESS_KEY
    secretName: vault
    secretKey: AWS_SECRET_ACCESS_KEY

service:
  enabled: false
