apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-env-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-env
        version: 0.1.2
        env: test
      annotations: {}
        # prometheus.io/scrape: "true"
        # prometheus.io/port: "8080"
    spec:
      containers:
      - image: damianjaniszewski/go-env:latest
        imagePullPolicy: IfNotPresent
        name: go-env
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
