apiVersion: v1
kind: Service
metadata:
  name: go-env
  labels:
    app: go-env
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    app: go-env
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-env
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-env
        version: 0.0.10
        env: test
      annotations: {}
        # prometheus.io/scrape: "true"
        # prometheus.io/port: "8080"
    spec:
      containers:
      - image: damianjaniszewski/go-env:latest
        imagePullPolicy: IfNotPresent
        name: go-env
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
